services:
  web:
    build: .
    volumes:
      - ./data:/app/data:ro
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  web-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./data:/app/data:ro
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    tty: true
    stdin_open: true