# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SPARQL_URL=http://mema_fuseki:3030

  web-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    tty: true
    stdin_open: true