# docker-compose.yml
x-logging: &default-logging
  driver: "local"
  options:
    max-size: "1m"
    max-file: "7"
    
services:
  memademo:
    image: memademo:0.1.3
    build:
      context: /home/mema/code/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MEMASTATS_URL: http://memastats:8118
        NEXT_PUBLIC_SPARQL_URL: http://mema_fuseki:3030
    container_name: memademo
    ports:
      - "3333:3000"
    networks:
      - mema_network
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_MEMASTATS_URL=http://memastats:8118
      - NEXT_PUBLIC_SPARQL_URL=http://mema_fuseki:3030
    depends_on:
      - mema_fuseki
    restart: unless-stopped
    logging: *default-logging

  web-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    tty: true
    stdin_open: true